### PR TITLE
Fix install-dependencies for openSUSE

### PR DESCRIPTION
**Pull request by th-otto**
"zypper update" is not the same as "apt-get update"; it would
try to install *all* packages for which updates are available

### CODE REVIEW

**Comment by probonopd** [comment]
Probably unrelated, build failed with `./build.sh: line 133: libtoolize: command not found`. https://travis-ci.org/AppImage/AppImageKit/jobs/273176457#L5734. Retriggering build.

**Comment by probonopd** [comment]
Indeed re-building solved the "issue".

**Comment by TheAssassin** [comment]
Thanks for your fix!

**Comment by probonopd** [comment]
Thank you very much @th-otto

**Comment by nandub** [comment]
@th-otto good catch, not sure how I missed that.  Thanks.

**Pull request merged**
