### PR TITLE
Fix a few more memory leaks

### PR DESCRIPTION
**Pull request by azubieta**

### CODE REVIEW

**Comment by azubieta** [comment]
fixes #492

**Comment by TheAssassin** [comment]
@azubieta is this still relevant? If yes, can you update this PR please?

**Comment by TheAssassin** [comment]
Do not merge yet: this PR needs to be rebased properly.

**Comment by TheAssassin** [comment]
I screwed up during the progress of rebasing. I cherry-picked out a commit which I am sure was part (or all) of this PR. I'll merge as soon as possible, to avoid further fiddling with this PR.

**Comment by probonopd** [comment]
Thank you @azubieta and @TheAssassin

**Pull request merged**
