### PR TITLE
Libappimage

### PR DESCRIPTION
**Pull request by azubieta**
The first implementation of lib appimage, with full test coverage.

### CODE REVIEW

**Comment by azubieta** [comment]
Commit 8bc82e0 is a bugfix

**Comment by probonopd** [comment]
Yay, this build succeeded. So can you explain a bit the motivation for a library, is it needed in order to be able to run tests?

Also, please have a look at the two minor issues listed at https://www.codacy.com/app/probonopd/AppImageKit/pullRequest?prid=1079028. Thanks!

**Comment by probonopd** [comment]
@TheAssassin what do you think about the minor issues reported at https://www.codacy.com/app/probonopd/AppImageKit/pullRequest?prid=1079028?

**Comment by TheAssassin** [comment]
@probonopd they should both be made `const std::string&`. But even if you ignore those warnings, wouldn't be a big deal.

**Comment by probonopd** [comment]
Can you do the edit?

**Comment by TheAssassin** [comment]
Thanks a lot, awesome job!

**Pull request merged**
