### PR TITLE
Make installation path of mksquashfs configurable (implements #612)

### PR DESCRIPTION
**Pull request by TheAssassin**

### CODE REVIEW

**Comment by TheAssassin** [comment]
@probonopd @azubieta review appreciated.

**Comment by probonopd** [comment]
While we are at it (stowing `mksquashfs` away in `/usr/lib/appimagekit/`), would it be a good time to do the same for `runtime` (to make cross-architecture AppImage generation easier)?

In this case, we should use architecture-dependent subdirectories of `/usr/lib/appimagekit/` (like https://wiki.debian.org/Multiarch/LibraryPathOverview#Multilib_suffixes - before this is implemented we should agree on _which_ architecture naming scheme we want to use, lib64, amd64, x86_64 - like always, the Linux world can't seem to agree...)

**Comment by TheAssassin** [comment]
We can do that, yes. But if we do want to do so, and also want to ship multiple runtimes for different architectures, I'd say we should build a separate package for the runtime. Then, we can build that package for all the different architectures, which can be installed separately on request.

This should go hand-in-hand with the plan to stop embedding runtimes in appimagetool, and moving on to using plain files.

**Comment by probonopd** [comment]
> I'd say we should build a separate package for the runtime.

I know why I don't like distro packaging... ;-)

**Comment by azubieta** [comment]
Packagers can always make a patch in order to change the install paths, so what ever you chose is OK as long as you set the separated paths for each arch.

**Pull request merged**
