### PR TITLE
Refactor and improve mountpoint name generation

### PR DESCRIPTION
**Pull request by TheAssassin**

### CODE REVIEW

**Comment by probonopd** [comment]
Please don't merge such PRs that change something that was not broken before without reviews and without explanation. 

For me such changes are a potential trouble source because they add the risk of breaking something without a pressing need to do so.

**Comment by TheAssassin** [comment]
This _was_ broken in the sense that when using `TARGET_APPIMAGE`, the mountpoint was created as `.mount_runtimXYZ`. The PR fixes that.

**Comment by TheAssassin** [comment]
Arguably, I could and should've done this as two commits, though.

**Comment by probonopd** [comment]
Thanks for the explanation. Generally please state what is being improved and why it needed to be improved.

**Pull request merged**
