### PR TITLE
Embed runtime in platform agnostic way

### PR DESCRIPTION
**Pull request by TheAssassin**
This PR implements the runtime embedding method suggested in #470. Instead of relying on ELF magic, the runtime is compiled into the appimagetool binary by converting it to C source code at first and then linking the compiled C code into the executable.

@teras we still have to work out how to do this on macOS, I'm still worried about cross-compiling the runtime to the Linux platform.

### CODE REVIEW

**Comment by probonopd** [comment]
> @teras we still have to work out how to do this on macOS, I'm still worried about cross-compiling the runtime to the Linux platform.

We could also just use plain old files...

**Comment by teras** [comment]
My point of view is we either abandon the elf-only approach of embedding the binary altogether or a multi-platform solution with potential should be found, in order the tool to be really multi-platform. And all this of course without dumping the external file..

**Comment by probonopd** [comment]
Who understands why the build fails?

**Comment by TheAssassin** [comment]
I fixed one build issue (wrong path in build script... I really don't like having to maintain both `build.sh` and CMake). The [new error](https://travis-ci.org/AppImage/AppImageKit/jobs/273391246#L1811) looks unrelated to my changes.

**Comment by probonopd** [comment]
Something pulls in Xft which fails. Whoever introduced a change that pulls in Xft needs to make sure Xft gets installed before the build starts. Then the error should go away and we can merge.

**Comment by TheAssassin** [comment]
@probonopd should we pick up the idea of this PR again? I still think it makes sense to "bake" in the runtime in a platform agnostic way, instead of relying on ELF magic. That'd allow for funny stuff like "let's cross compile it for macOS but embed a Linux runtime".

**Comment by probonopd** [comment]
I think the easiest way is to have runtime files for each architecture as separate files located at a path relative to the main `linuxdeployqt` binary like `{ARGV0}/../../share/appimagekit/...` and use them from there.

**Comment by TheAssassin** [comment]
This just opens a possibility. The main intention is to embed the Linux version during the Linux build without ELF magic. I'm not attempting to provide such "combined" AppImages.

**Comment by probonopd** [comment]
What do you mean by "ELF magic"? I think the solution advocated by me (namely, using plain old files) does not need any "ELF magic".

**Comment by TheAssassin** [comment]
You're missing the point a bit. The PR attempts to replace the *embedding* of the runtime we *have* at the moment in appimagetool. Currently, the runtime is embedded in an ELF header section. The PR changes this to a platform agnostic (i.e., does not depend on the ELF format, and would work on macOS, Windows, ...) way.

This would open possibilities like the ones I mentioned, but the PR strictly focuses on what I described above. You should probably re-read the thread, and maybe #470, to get an idea of what this is about and what it is *not* about.

**Comment by probonopd** [comment]
> The PR attempts to replace the embedding of the runtime we have at the moment in appimagetool. 

Yes, I had originally thought that embedding the runtime was a good idea (and hence initially implemented it that way), but I am no longer convinced that it is (but plain old files may be easier for users). So I don't see this PR as a high priority at the moment, and could imagine switching to files in the future.

**Comment by TheAssassin** [comment]
In my opinion, it makes sense to bundle one (or more) runtimes with appimagetool. Adding that tiny step of complexity will just annoy people, as they no longer just need to download appimagetool but also the suitable runtime.

**Comment by probonopd** [comment]
...which we would make part of the AppImage, of course...

**Comment by TheAssassin** [comment]
I see. However, people building their own versions of appimagetool won't be happy about the

**Comment by TheAssassin** [comment]
I guess we won't be needing this any more. Closing.

**Pull request closed without merging**
