### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jospoortvliet**
fix link?!?!

### CODE REVIEW

**Comment by TheAssassin** [comment]
Good catch, thanks. I wonder whether GitHub have removed that, because I'm pretty certain this link used to work.

**Comment by KurtPfeifle** [comment]
Opening in a browser:

(1) Old link: https://github.com/AppImage/AppImageUpdate/releases/download/continuous/ 
(2) Jos' link: https://github.com/AppImage/AppImageUpdate/releases/tag/continuous
(3) My link: https://github.com/AppImage/AppImageUpdate/releases/

The first indeed doesn't work. However, (2) and (3) currently deliver the same page to me. Wouldn't it be better to use (3)? First of all, for general simplicity reasons? Also, because users there could pick from different tagged or continuous releases (should there ever be such differences)?

**Comment by TheAssassin** [comment]
We only have the continuous release at the moment, so I don't see a problem there at the moment.
CC @probonopd

**Comment by probonopd** [comment]
I don't see any remaining problem anymore either, feel free to reopen if you think something still needs to be fixed.

**Pull request merged**
