### PR TITLE
runtime: fix double fclose() on sqfs read error

### PR DESCRIPTION
**Pull request by Adam-**

### CODE REVIEW

**Review by TheAssassin — APPROVED** [review]

**Comment by TheAssassin** [comment]
Thanks!

**Comment by probonopd** [comment]
Thank you very much @Adam- and @TheAssassin.

**Review by Bolshau — CHANGES_REQUESTED** [review]
b181fc409a69fc2fede12e3a5cf0c0b76e7ebfd6

**Comment by probonopd** [comment]
I don't understand your comment @Bolshau, can you elaborate? Thanks.

**Review by Bolshau — APPROVED** [review]

**Pull request merged**
