### PR TITLE
Improve Chinese translation

### PR DESCRIPTION
**Pull request by boris1993**

### CODE REVIEW

**Comment by TheAssassin** [comment]
Thanks for your PR. It is reviewed at the moment. Next time, please use our Weblate instance, https://translate.assassinate-you.net/projects/appimage/website/zh/.

**Comment by shouhuanxiaoji** [comment]
hi, 欢迎你的加入，坦白说，之前有些问题。。导致部分翻译在提交后出现了偏差，例如“尝试地下AppImage”不是我们本来的翻译，原翻译应该是“尝试一下AppImage”。
你也可以加入中文本地化翻译团队，在tg频道#gamuxzh或qq群300610898，两个频道信息是互通的

**Comment by TheAssassin** [comment]
Thanks.

**Comment by boris1993** [comment]
I asked probono on how to participate in the translation, then he sent me this GitHub repo and told me I can send a Pull Request. So I thought you are not using any translation platform. I'll use the Weblate next time. Sorry for the inconvenience. @TheAssassin 

之前不知道这个项目用了翻译平台，所以还以为是机翻 😂 @shouhuanxiaoji

**Comment by probonopd** [comment]
Yes, sorry, my mistake.

Please document how participants like @boris1993 can improve the translations. I was not aware that everyone can use Weblate.

**Comment by TheAssassin** [comment]
Never mind, @boris1993, it's all fine.

@probonopd of course everyone can use it, that's the purpose of such platforms.

**Pull request merged**
