### PR TITLE
Fix/wrong architecture string on appimagetool arch/1114

### LINKED ISSUE #1114: Misleading architecture string for arm on appimagetool
`appimagetool` expects `arm_aarch64` as architecture string for `aarch64` and arm for `armhf`. Is there an special reason for this name changes? From my point of view it's extremely misleading considering that the binaries are published using `aarch64` and `armhf`.

https://github.com/AppImage/AppImageKit/blob/master/src/appimagetool.c#L362

### PR DESCRIPTION
**Pull request by azubieta**
Allows using armhf and aarch64 as architecture names on appimagetool. Doesn't remove the old names ("arm", "arm_aarch64") to avoid breaking scripts of possible users.

Closes #1114

### CODE REVIEW

**Comment by probonopd** [comment]
Why do you want to hardcode `pathToMksquashfs = "/usr/bin/mksquashfs";`?

**Comment by azubieta** [comment]
> Why do you want to hardcode

Ups, that's wrong

**Comment by azubieta** [comment]
Should I proceed with the merge?

**Comment by probonopd** [comment]
Lgtm. @TheAssassin?

**Comment by probonopd** [comment]
Is this still a thing? @TheAssassin wdyt?

**Comment by hyh19962008** [comment]
I totally agreed "arm_aarch64" is misleading, and the command-line help message doesn't provide this information, you have to look into the source code to find it.

**Comment by adrianinsaval** [comment]
any reason why this hasn't been merged? @probonopd

**Comment by probonopd** [comment]
Waiting for @TheAssassin to review this.

**Comment by adrianinsaval** [comment]
apparently appimagetool is now maintained at https://github.com/AppImage/appimagetool? these change appears to be already included there. I tried the appimage from there and it worked. It would be useful if that gets mentioned in the issues for this reported in this repo #1114 and #1163, to help people googling around like me.

**Comment by TheAssassin** [comment]
Yep, makes no sense to work on this PR here. IF the changes would be required, someone needs to open a PR there. I think you even opened a PR there recently.

**Comment by TheAssassin** [comment]
Yup. See https://github.com/AppImage/appimagetool/pull/54.

**Pull request closed without merging**
