### PR TITLE
X-AppImage-Version

### PR DESCRIPTION
**Pull request by TheAssassin**
Implements #672.

### CODE REVIEW

**Comment by probonopd** [comment]
Alternatively, we could not use `g_key_file_save_to_file` and implement the needed functionality on our own. May be less problematic.

**Comment by TheAssassin** [comment]
> Alternatively, we could not use g_key_file_save_to_file and implement the needed functionality on our own. May be less problematic.

If it was possible to "easily" implement this functionality, we wouldn't use GLib for it, @probonopd...

**Comment by TheAssassin** [comment]
I will try to build a custom GLib in the AppImageBuild containers, and ship GLib with appimagetool. It's the only viable solution.

**Comment by TheAssassin** [comment]
The library part was fairly easy, and it seems like the appimagetool part is finished now, too. Merging asap.

**Pull request merged**
