### PR TITLE
Added an option for reproducible builds

### PR DESCRIPTION
**Pull request by Mailaender**
This is an ongoing quest on @openSUSE build service. We hacked something together quickly, but I saw others are also interested.

Closes https://github.com/AppImage/AppImageKit/issues/625
Closes https://github.com/AppImage/AppImageKit/issues/929

### CODE REVIEW

**Comment by probonopd** [comment]
Lgtm, what do you think @TheAssassin?

**Review by TheAssassin — CHANGES_REQUESTED** [review]
The `if`-ed options clash with the output variables. Also, they're not defined as `option`s. They also look like the check should be reversed.

We don't want our builds to be reproducible. I don't see why you would change the build script.

**Comment by Mailaender** [comment]
See https://en.opensuse.org/openSUSE:Reproducible_Builds

**Comment by TheAssassin** [comment]
I don't question that you may need it. But you changed `build.sh`, which I don't understand. The reason we embed these data is actually to have some meaningful versioning. The issue system relies on that.

Regarding git hash, embedding them should not harm reproducibility anyway. If you build the same commit, it'll provide the same git hash. I can understand why you don't want the date, though. AppImages are built reproducibly, too, we instruct `mksquashfs` not to set a date.

The point is that the patch you provided just lacks some quality, and changes things that influence the build. I figured you'd likely not use `build.sh` (which is not even available any more). Perhaps you do?

**Comment by TheAssassin** [comment]
Please note that I would welcome a reproducible build option upstream. I didn't mean to reject your feature, but rather improve the implementation.

**Pull request closed without merging**
