### PR TITLE
Fix potential library path injection vulnerability

### PR DESCRIPTION
**Pull request by Lekensteyn**
While inspecting the code after #891, I noticed a potential insecure path construction as explained in the commit message:

*    Avoid injecting the current directory into paths

    If LD_LIBRARY_PATH was previously not set, it could end up as:

        LD_LIBRARY_PATH=.../lib64/:

    which might result in querying the current working directory for
    libraries. Use the "Use Alternative Value" parameter expansion (POSIX
    Shell standard) to expand to an empty value (if the value is empty or
    unset) and to `:$LD_LIBRARY_PATH` otherwise.

    This patch was created with this eye-bleeding command to avoid typos:

        sed -r 's/:"\$\{([A-Z_]+)\}"$/"${\1:+:$\1}"/' resources/AppRun

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks for your careful review. Could you give an example where the original leads to problems?

**Comment by Lekensteyn** [comment]
`PATH` is unlikely to be empty, but `LD_LIBRARY_PATH` might be empty. This can result in the following scenario:

1. Assume a binary which is linked with libz.so.1.
2. Assume that the App Image does not ship with libz.so.1
3. Assume that an attacker has placed a malicious libz.so.1 in the current working directory (e.g. in ~/Downloads).
4. A user who runs the App Image from the file browser (with the current working directory set to ~/Downloads) will then load the malicious libz.so.1 library due to `LD_LIBRARY_PATH` containing the current directory.

(I did not look at the other variable names, but they might be affected by a similar issue if the empty path component has a special meaning.)

**Comment by probonopd** [comment]
Maybe I am slow, but I still don't see why/how `cwd` would end up in `LD_LIBRARY_PATH`.

**Comment by Lekensteyn** [comment]
Travis seems failing for unrelated reasons, isn't it?

**Comment by probonopd** [comment]
The issue was that this is a pull request and pull requests do not get the signing keys. The build system _should_ not attempt to sign pull request builds, but it did. I hope it has been fixed in the meantime.

```
gpg2 and sha256sum are installed and user requested to sign, hence signing
/usr/bin/sha256sum appimagetool-x86_64.AppImage
/usr/bin/gpg2 --batch --detach-sign --armor   appimagetool-x86_64.AppImage.digest
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

**Pull request merged**
