### PR TITLE
Fix command existence check

### LINKED ISSUE #493: Desktop integration does not work anymore
Commit 09a48ee8bf5644fd6505588662efc390fb910d4f breaks the desktop integration.
Check for command existence is invalid as it always returns empty string (line 151).
It would be better to check it with `[ -x "$(command -v $DEP)" ]`

### PR DESCRIPTION
**Pull request by knapsu**
Fixes #493

### CODE REVIEW

**Comment by TheAssassin** [comment]
The `set +e`, but especially `set -e` (which forces `-e`, whether it was set before the block or not) might cause a lot of confusion to the users. I understand that the `which` command shall be allowed to fail. Instead of using the `set`s, have you tried `|| true` for that single `which` command? That'd be less confusing, and should have the same effect.

**Comment by knapsu** [comment]
OK. I've modified the source to avoid using the set builtin command. `|| true` will not work as it will make `$?` return always true.

**Comment by TheAssassin** [comment]
Thanks!

**Comment by probonopd** [comment]
Thank you.

**Pull request merged**
