### PR TITLE
Remove null characters from --appimage-updateinformation output

### LINKED ISSUE #621: Shell output of `--appimage-updateinfo` is padded with NUL byte
I noticed that all AppImages released by the AppImageKit project pad the string printed for *`--appimage-updateinfo`* to fill up to 1024 characters with NUL bytes. It doesn't normally show in the terminal, but it is revealed as a series of *`@@@@@@@@@@...`* if you run, for example:

    ./appimagetool-x86_64.AppImage --appimage-updateinfo | less

For what reason are these NUL bytes required in the *output* (when printing the updatestring *AS INFO* into the terminal, as response to a command line argument requesting it)?

Can't these bytes be suppressed before they arrive in the shell? They only make using the *`--appimage-updateinfo`* output harder to post-process in scripts and logs...

### PR DESCRIPTION
**Pull request by TheAssassin**
Fixes #621.

### CODE REVIEW

**Comment by KurtPfeifle** [comment]
This PR is not yet pulled, so standard releases are not suitable to test this. From the automatic Travis check builds I cannot find a ready-built AppImage for ***x86_64*** to test with. In the log file (https://travis-ci.org/AppImage/AppImageKit/jobs/333185864), for example for *`appimagetool`* I only find this ***i686*** link in line 4239:  https://transfer.sh/7bQwH/appimagetool-i686.AppImage.

## BTW, line 3638 also doesn't look healthy + convincing to me:

```
./appimagetool.AppDir/AppRun ./appimagetool.AppDir/ -s -v -u 'gh-releases-zsync|AppImage|AppImageKit|continuous|appimagetool-x86_64.AppImage.zsync' appimagetool-i686.AppImage
```

Do you see it? There is a mixture of x86_64 and i686 in that line (*an i686 AppImage being built with an update-string referring to an x86_64 .zsync file*), which doesn't look quite right to me.

**Comment by probonopd** [comment]
On https://travis-ci.org/AppImage/AppImageKit/builds/333185861 there are two builds, one for each architecture. The x86_64 one has

https://transfer.sh/zznho/appimagetool-x86_64.AppImage

**Comment by TheAssassin** [comment]
An AppImage generated with the new appimagetool: https://transfer.sh/sItfI/test.AppImage
Same AppImage generated with current master (appimagetool, continuous build (commit continuous-3-gfb6725a), build 1426 built on 2018-01-25 17:59:28 UTC): https://transfer.sh/Mk4Ht/test-old.AppImage

I still can't see a difference in my shell window, but `wc` reveals the patch seems to work:
```
test> ./test-old.AppImage --appimage-updateinformation | wc 
      1       1    1025
test> ./test.AppImage --appimage-updateinformation | wc 
      1       1      38
test> ./test.AppImage --appimage-updateinformation 
zsync|https://test.test/test.AppImage
```

It's actually 37 characters, but taking the one newline character (`\n`) into account, it's 38, so it seems to work as intended now.

@KurtPfeifle can you confirm this, please? I'd like to merge this PR today.

**Comment by KurtPfeifle** [comment]
The AppImage from https://transfer.sh/sItfI/test.AppImage, when running command:

    test.AppImage --appimage-updateinfo | less 

doesn't display the nul characters as ***`^@^@^@...`*** any longer.

Merge!

**Pull request merged**
