### PR TITLE
Read e_machine elf file header field instead of using an external tool

### LINKED ISSUE #312: [32-bit] appimagetool names architecture wrongly
We want `i686` as part of the filename for [32-bit](https://github.com/probonopd/AppImageKit/pull/307) Intel AppImages, but `appimagetool` names them `appname-version-Intel_80386.AppImage`. This is on Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by azubieta**
Fix #312 
Using an external tool like `file`, `objdump`, `readelf` is much more inefficient than reading the elf header ourselves. Also it's not more reliable according to the number of bugs that we have because of them.

### CODE REVIEW

**Comment by TheAssassin** [comment]
Thanks for the contribution. I'd prefer it to be in libappimage so other projects could make use of it, too.

**Comment by probonopd** [comment]
Does this work for all architectures, which ones have been tested so far?

**Comment by azubieta** [comment]
This works only for the the following architectures: https://github.com/AppImage/AppImageKit/blob/194569c02a243efc3a83be14befdc6870560292f/src/appimagetool.c#L65
Which are the ones suported by appimagetool.
I was tested on x86_64 and i386.

**Comment by TheAssassin** [comment]
@probonopd this was built following the ELF specification, so it _should_ work. Definitely more reliable than any form of external tool called via subprocess.

**Comment by probonopd** [comment]
We should also test arm 32-bit and arm 64-bit if possible. Thanks!

**Comment by TheAssassin** [comment]
Thanks @azubieta.

**Pull request merged**
