### PR TITLE
fix not follow symlinks when searching for arch type in appimagetool

### PR DESCRIPTION
**Pull request by teras**
Should solve issue https://github.com/AppImage/AppImageKit/issues/546

### CODE REVIEW

**Comment by probonopd** [comment]
Hi @teras, by just looking at the code I fear that we are still traversing the whole tree (following symlinks), which can take forever if a symlink points to / or something like that. Correct?

Would there a way to not follow symlinks when traversing the tree?

**Comment by teras** [comment]
What about now?

**Comment by probonopd** [comment]
Looks good to me. Let's see how it performs.

**Comment by probonopd** [comment]
Thank you very much @teras

**Pull request merged**
