### PR TITLE
Improve --help output

### PR DESCRIPTION
**Pull request by KurtPfeifle**
Try to make '--help' more precise. (Dunno if this then still compiles -- my only way to tell is press the big green button and hope for not harvesting too many red signals and texts in return....)

### CODE REVIEW

**Comment by TheAssassin** [comment]
Is `SRC` something normal users would understand as "source"? If not, I'd suggest to replace it with `SOURCE`. The other upper-case words aren't abbreviated either.

**Comment by TheAssassin** [comment]
@KurtPfeifle unfortunately your changes don't work as intended with the GLib option parser.

See https://travis-ci.org/AppImage/AppImageKit/jobs/335667955#L3527. The new options would be e.g., `"--list SRC" <real value>`. This is probably not what you wanted.

**Comment by TheAssassin** [comment]
Whoops. I hit Ctrl+Enter too early.

`'l SRC'` further breaks the C(++) syntax. `Single quotes can be used to express a single character (type `char`), whereas double quotes are used for strings (type `char[]` (read: `char` array)).

This limitation cannot be circumvented as far as I can see, unless we introduce another option parser (which would introduce another dependency, etc.).

Please revise your PR.

**Comment by probonopd** [comment]
> unless we introduce another option parser (which would introduce another dependency, etc.)

Let's avoid that...

**Comment by alshhrymhmd008** [comment]
Dlryy

**Comment by alshhrymhmd008** [comment]
Tih

**Pull request closed without merging**
