### PR TITLE
[WIP] Chinese translation of appimage.org

### PR DESCRIPTION
**Pull request by TheAssassin**
The people at @Gamuxorg have been working on translating the AppImage homepage appimage.org (stored within the `gh-pages` branch in the AppImageKit repository). This is a work in progress. Please do not merge yet.

The PR, when merged, will add the translations to a new branch `gh-pages-cn`. We can then decide how to deploy them. There's a few options, like, automatically switching to the translation page when the browser has set Chinese as their default language, deploying to a subdomain (cn.appimage.org), etc.

### CODE REVIEW

**Comment by probonopd** [comment]
Can we set up the hosting so that it shows Chinese when the browser requests it using the Accept-Language header?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

**Comment by probonopd** [comment]
I would prefer the same URL for all languages, and detecting the language of the browser to decide which version to deliver.

**Comment by TheAssassin** [comment]
@probonopd I just asked @Gamuxorg to do it this way because it wasn't really complicated to set up, and easy to translate. We can move the data over to the gh-pages branch at any time.

**Comment by shouhuanxiaoji** [comment]
down

**Comment by TheAssassin** [comment]
@shouhuanxiaoji big thanks to you and the team of @Gamuxorg. We've imported the translation into our Weblate system at https://translate.assassinate-you.net/projects/appimage/website/zh/.

Please use Weblate for future changes. We are going to use the data in Weblate for generating the website.

**Pull request closed without merging**
