### PR TITLE
Enable portable home/config dirs for extract-and-run

### PR DESCRIPTION
**Pull request by xordspar0**

### CODE REVIEW

**Review by TheAssassin — COMMENTED** [review]
Looks good to me. Please fix the deployment step as shown [here](https://github.com/AppImageCommunity/AppImageUpdate/pull/219/commits/56bc58bfad2295a309aca8059976c9a3ddd3d539) so we can proceed to merging this PR.

**Review by TheAssassin — CHANGES_REQUESTED** [review]
See above.

**Comment by probonopd** [comment]
This is a reminder that we should move to https://github.com/AppImage/type2-runtime sooner or later, so that we don't have to do a lot of backporting like this one.

**Comment by xordspar0** [comment]
> Please fix the deployment step

Done. Hopefully the build is good now.

> This is a reminder that we should move to https://github.com/AppImage/type2-runtime rather sooner than later, so that we don't have to do a lot of backporting like this one.

I look forward to that. I'll backport the fix to type2-runtime right away.

**Review by TheAssassin — APPROVED** [review]

**Comment by TheAssassin** [comment]
Thanks!

**Pull request merged**
