### PR TITLE
Fix potential cause of issues reported in #581

### PR DESCRIPTION
**Pull request by TheAssassin**

### CODE REVIEW

**Comment by TheAssassin** [comment]
After merging #568, we should be able to finish and merge this PR as soon as possible.

**Comment by TheAssassin** [comment]
The PR builds fine now. The resulting appimaged AppImage works fine on CentOS 6 now, but I still see issues on newer distros. @azubieta please review.

**Comment by probonopd** [comment]
On Ubuntu 17.10 with 598a8f1 getting

```
me@host:~$ '/home/me/Downloads/appimaged-x86_64(1).AppImage' 
_________________________

-> REGISTER /home/me/Downloads/appimaged-x86_64(1).AppImage
squashfs based type 2 AppImage
Got root desktop: appimaged.desktop
.upd_info offset: 111896
.upd_info length: 1024
*** Error in `appimaged': munmap_chunk(): invalid pointer: 0x0000000000430832 ***
Aborted
```

**Comment by TheAssassin** [comment]
Yes, I've seen that. After merging #568, #581 should build again. As #582 is having the same issue, if #581 fixes the issue, we'll merge the revert.

**Comment by TheAssassin** [comment]
Closing as #581 has been merged.

**Pull request closed without merging**
